#!/usr/bin/env bash
#
# Quick start for the Autonomous Engineering Intelligence Platform.
#
#   ./start.sh          start backend + frontend
#   ./start.sh stop     stop whatever this script started
#   ./start.sh status   show what is running
#
# The backend's default port (8000) is often taken by an unrelated service, so
# a free port is picked automatically and the frontend is pointed at it.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV="$ROOT/.venv"
RUN_DIR="$ROOT/.run"
BACKEND_PREFERRED_PORT="${AEIP_BACKEND_PORT:-8000}"
FRONTEND_PORT="${AEIP_FRONTEND_PORT:-3000}"

mkdir -p "$RUN_DIR"

c_g() { printf '\033[32m%s\033[0m\n' "$*"; }
c_y() { printf '\033[33m%s\033[0m\n' "$*"; }
c_r() { printf '\033[31m%s\033[0m\n' "$*"; }

port_busy() {
  # 0 = in use. ss is checked first; fall back to bash's /dev/tcp probe.
  if command -v ss >/dev/null 2>&1; then
    ss -ltn 2>/dev/null | awk '{print $4}' | sed 's/.*://' | grep -qx "$1"
  else
    (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null && { exec 3<&-; return 0; } || return 1
  fi
}

find_free_port() {
  local p="$1"
  for _ in $(seq 0 40); do
    port_busy "$p" || { echo "$p"; return 0; }
    p=$((p + 1))
  done
  c_r "No free port found starting at $1" >&2
  return 1
}

stop_stack() {
  local stopped=0
  for name in backend frontend; do
    local pidfile="$RUN_DIR/$name.pid"
    [ -f "$pidfile" ] || continue
    local pid
    pid="$(cat "$pidfile")"
    if kill -0 "$pid" 2>/dev/null; then
      # Kill the whole process group; next/uvicorn --reload spawn children.
      kill -TERM -- "-$pid" 2>/dev/null || kill -TERM "$pid" 2>/dev/null || true
      sleep 1
      kill -0 "$pid" 2>/dev/null && kill -KILL -- "-$pid" 2>/dev/null || true
      c_g "Stopped $name (pid $pid)"
      stopped=1
    fi
    rm -f "$pidfile"
  done
  [ "$stopped" -eq 1 ] || c_y "Nothing was running."
}

show_status() {
  for name in backend frontend; do
    local pidfile="$RUN_DIR/$name.pid"
    if [ -f "$pidfile" ] && kill -0 "$(cat "$pidfile")" 2>/dev/null; then
      c_g "$name: running (pid $(cat "$pidfile"))  log: .run/$name.log"
    else
      c_y "$name: not running"
    fi
  done
  [ -f "$RUN_DIR/backend.url" ] && echo "backend url: $(cat "$RUN_DIR/backend.url")"
  return 0
}

case "${1:-start}" in
  stop)   stop_stack; exit 0 ;;
  status) show_status; exit 0 ;;
  start)  ;;
  *)      c_r "Usage: $0 [start|stop|status]"; exit 2 ;;
esac

# ── Preflight ────────────────────────────────────────────────────────────────
[ -x "$VENV/bin/python" ] || { c_r "No virtualenv at $VENV — run: python -m venv .venv && .venv/bin/pip install -e '.[dev]'"; exit 1; }
[ -d "$ROOT/frontend/node_modules" ] || { c_y "Installing frontend dependencies..."; (cd "$ROOT/frontend" && npm install); }

# Refuse to double-start.
if [ -f "$RUN_DIR/backend.pid" ] && kill -0 "$(cat "$RUN_DIR/backend.pid")" 2>/dev/null; then
  c_y "Already running. Use '$0 stop' first, or '$0 status'."
  exit 0
fi

# Ollama is the configured LLM provider; the graph stalls without it.
if grep -qi '^LLM_PROVIDER *= *"\?ollama' "$ROOT/.env" 2>/dev/null; then
  if ! curl -sf -m 3 "${OLLAMA_BASE_URL:-http://localhost:11434}/api/tags" >/dev/null 2>&1; then
    c_y "Warning: Ollama is not reachable — investigations will fail at the planner."
    c_y "         Start it with: ollama serve"
  fi
fi

BACKEND_PORT="$(find_free_port "$BACKEND_PREFERRED_PORT")"
[ "$BACKEND_PORT" = "$BACKEND_PREFERRED_PORT" ] || \
  c_y "Port $BACKEND_PREFERRED_PORT is taken — using $BACKEND_PORT instead."

BACKEND_URL="http://localhost:$BACKEND_PORT"
echo "$BACKEND_URL" > "$RUN_DIR/backend.url"

# The browser calls the backend directly, so the URL must be baked in here.
# Written every start so the frontend always follows the chosen port.
printf '# Generated by start.sh — do not edit; re-run ./start.sh to update.\nNEXT_PUBLIC_API_BASE_URL=%s\n' \
  "$BACKEND_URL" > "$ROOT/frontend/.env.local"

# ── Backend ──────────────────────────────────────────────────────────────────
c_y "Starting backend on $BACKEND_URL ..."
(
  cd "$ROOT/backend"
  setsid "$VENV/bin/uvicorn" app.main:app --host 0.0.0.0 --port "$BACKEND_PORT" \
    > "$RUN_DIR/backend.log" 2>&1 < /dev/null &
  echo $! > "$RUN_DIR/backend.pid"
)

for _ in $(seq 1 60); do
  curl -sf -m 2 "$BACKEND_URL/health" >/dev/null 2>&1 && break
  sleep 1
done
if ! curl -sf -m 2 "$BACKEND_URL/health" >/dev/null 2>&1; then
  c_r "Backend failed to start. Last lines of .run/backend.log:"
  tail -20 "$RUN_DIR/backend.log"
  stop_stack
  exit 1
fi
c_g "Backend healthy at $BACKEND_URL"

# ── Frontend ─────────────────────────────────────────────────────────────────
FRONTEND_PORT="$(find_free_port "$FRONTEND_PORT")"
c_y "Starting frontend on http://localhost:$FRONTEND_PORT ..."
(
  cd "$ROOT/frontend"
  setsid npm run dev -- --port "$FRONTEND_PORT" \
    > "$RUN_DIR/frontend.log" 2>&1 < /dev/null &
  echo $! > "$RUN_DIR/frontend.pid"
)

frontend_up=0
for _ in $(seq 1 90); do
  if curl -sf -m 2 "http://localhost:$FRONTEND_PORT" >/dev/null 2>&1; then
    frontend_up=1
    break
  fi
  sleep 1
done

FRONTEND_URL="http://localhost:$FRONTEND_PORT"
if [ "$frontend_up" -eq 1 ]; then
  # npm spawns next through a shell, so the recorded $! has already exited.
  # Track the process actually listening, so stop/status work.
  listener="$(ss -ltnp 2>/dev/null | grep -oP "(?<=:$FRONTEND_PORT\s).*pid=\K[0-9]+" | head -1)"
  [ -n "$listener" ] && echo "$listener" > "$RUN_DIR/frontend.pid"
elif grep -q "You can access the existing server" "$RUN_DIR/frontend.log" 2>/dev/null; then
  # Next refuses to start a second dev server for the same project and prints
  # where the running one lives. Reuse it rather than reporting a bogus URL.
  existing="$(grep -oE 'http://localhost:[0-9]+' "$RUN_DIR/frontend.log" | head -1)"
  rm -f "$RUN_DIR/frontend.pid"
  c_y "A Next dev server for this project is already running at ${existing:-an existing port}."
  c_y "It was not started by this script, so it still points at its own backend URL."
  c_y "Restart it to pick up $BACKEND_URL, or stop it and re-run ./start.sh."
  FRONTEND_URL="${existing:-unknown}"
else
  c_r "Frontend did not come up. Last lines of .run/frontend.log:"
  tail -20 "$RUN_DIR/frontend.log"
  FRONTEND_URL="not running"
fi

echo
c_g "AEIP is up."
echo "  UI:       $FRONTEND_URL"
echo "  API:      $BACKEND_URL"
echo "  API docs: $BACKEND_URL/api/v1/docs"
echo "  Logs:     .run/backend.log  .run/frontend.log"
echo "  Stop:     ./start.sh stop"
